### ISSUE TITLE
@kind/feature - Add the address for the smart contract for staking, lockup, ALCA and others

### ISSUE THREAD

**Issue by vtleonardo** [alicenet/ui#151]
**Is your feature request related to a user or engineer story?** : User || Engineer

**What story does this feature enable?**
As a user/engineer, I would like to have the address of the smart contracts in the frontend to increase trustability. Ideally, the addresses should be a link to the etherscan page where we can see the smart contracts' source code. This way, users will know that we are indeed using a smart contract that can be trusted. 

The following smart contracts should be added:
- ALCA
- Public Staking contract
- Lockup
- Staking Router V1
- MAD
- ALCB (once is deployed).

The links for the contracts can be found on the [alicenet wiki](https://github.com/alicenet/alicenet/wiki) after the production deployment.

**Comment by ACatThatPrograms** [comment]
We can add this information to the help modal under the **Welcome**  views. as _Relevant Smart Contracts_

All but ALCB should be listed there.
